### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by Youbi42** [blakevanlan/KingdomCreator#38]
Hello,
I’m trying to integrate the french translation. I have cloned the repo, checkout a branch and created the src/i18n/ required files, but I don’t know how to integrate that.
What is the process?
I’m running a local instance of KingdomCreator to test my changes.

Regards

-- 
Youbi

**Comment by blakevanlan** [comment]
Hi Youbi,

Thanks for the help!

The French translations aren't fully setup yet since they weren't complete. Here's a few places you'll need to change:
1. Add `i18n/fr.ts` - Use `i18n/de.ts`([source](https://github.com/blakevanlan/KingdomCreator/blob/master/src/i18n/de.ts)) as an example - this file is what pulls in all the translations for a given language
2. Update `i18n/language.ts` ([source](https://github.com/blakevanlan/KingdomCreator/blob/master/src/i18n/language.ts)) - Add French as a language 

Once you've done that, you should see a link for French show up in the site footer!

**Comment by Youbi42** [comment]
Thanks!

I created `fr.ts` and updated `language.ts`, but I still can’t see the link for French.
I think that I may be wrong from the beginning:
How am I supposed to host KingdomCreator?
As for now, I only have a webserver (Apache) delivering the `docs/` folder.
Is there any step I should add to process the TypeScript files?

**Comment by blakevanlan** [comment]
I'll update the README with instruction but here are the commands to run:
`npm start` - Run the development server with hot reloading at `localhost:8080`
`npm run build` - Builds the site and outputs the assets in `/docs`
`npm serve-static` - Serves the build assets from `/docs` in case you want to check the built version

My guess is you're not seeing the changes because you haven't run `npm run build` yet and are serving the built assets from `/docs`?

**Comment by Youbi42** [comment]
You’re right, I haven’t built anything!
I’ll build and try again :)

**Comment by Youbi42** [comment]
The build (`npm run build`) fails with the following errors:

```
ERROR in ./src/components/Randomizer.vue?vue&type=script&lang=ts& (./node_modules/ts-loader??ref--1!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Randomizer.vue?vue&type=script&lang=ts&)
Module not found: Error: Can't resolve './Addons.vue' in '/home/youbi/sources/KingdomCreator/src/components'
 @ ./src/components/Randomizer.vue?vue&type=script&lang=ts& (./node_modules/ts-loader??ref--1!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Randomizer.vue?vue&type=script&lang=ts&) 42:0-34 112:24-30
 @ ./src/components/Randomizer.vue?vue&type=script&lang=ts&
 @ ./src/components/Randomizer.vue
 @ ./node_modules/ts-loader??ref--1!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Index.vue?vue&type=script&lang=ts&
 @ ./src/views/Index.vue?vue&type=script&lang=ts&
 @ ./src/views/Index.vue
 @ ./src/index-page.ts
 @ multi ./src/index-page.ts ./styles/index.styl

ERROR in ./src/components/Randomizer.vue?vue&type=script&lang=ts& (./node_modules/ts-loader??ref--1!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Randomizer.vue?vue&type=script&lang=ts&)
Module not found: Error: Can't resolve './Boons.vue' in '/home/youbi/sources/KingdomCreator/src/components'
 @ ./src/components/Randomizer.vue?vue&type=script&lang=ts& (./node_modules/ts-loader??ref--1!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Randomizer.vue?vue&type=script&lang=ts&) 43:0-32 113:23-28
 @ ./src/components/Randomizer.vue?vue&type=script&lang=ts&
 @ ./src/components/Randomizer.vue
 @ ./node_modules/ts-loader??ref--1!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Index.vue?vue&type=script&lang=ts&
 @ ./src/views/Index.vue?vue&type=script&lang=ts&
 @ ./src/views/Index.vue
 @ ./src/index-page.ts
 @ multi ./src/index-page.ts ./styles/index.styl
```

I can’t find the files `Boons.vue` and `Addons.vue`, but the following files exists:
```
src/components/addons.vue 
src/components/boons.vue
```

I branched from master, should I merge another branch which fixes this typo?

**Comment by blakevanlan** [comment]
I actually just removed `addons.vue` in PR #39. Git is funky with renaming files and I renamed `boons.vue` to `Boons.vue` but it looks like Git didn't actually pick up the change. I'll try and fix that again now.

**Comment by blakevanlan** [comment]
Just pushed a commit to rename the file. `master` should be working for you again.

**Comment by Youbi42** [comment]
I pulled and merged master into my dev branch, but there is still an error regarding `Addons.vue` not existing.
I copied `addons.vue` to `Addons.vue` to fix that, but one error still remains:

```
ERROR in /home/youbi/sources/KingdomCreator/src/settings/settings.ts
[tsl] ERROR in /home/youbi/sources/KingdomCreator/src/settings/settings.ts(63,32)
      TS7053: Element implicitly has an 'any' type because expression of type 'any' can't be used to index type 'typeof SortOption'.
```

May it be related to my node version?
```
% npm --version node
6.13.4
% npm view node version
13.10.1
```

**Comment by blakevanlan** [comment]
I should move this to building in Docker for convenience. 

Potentially. That looks like a TypeScript error though so probably has more to do with the version of TypeScript. 

Just pushed a [fix](https://github.com/blakevanlan/KingdomCreator/commit/4e482f4a79c12874c56777cf06b7a491442aca63) for the issue. Not sure why it wasn't failing for my build.

**Comment by Youbi42** [comment]
You rock!
I can now successfully build the assets :)
Language switching actually works, but all is still in english.
I will check everything before coming back to you.

**Comment by blakevanlan** [comment]
Great! 😄 Let me know if you get stuck.

**Comment by Youbi42** [comment]
Hello!
Still no success when language is French.
None of the translations are applied.
How can I clean the `docs/` directory? I would like to clean any outdated asset.

Can I propose a merge request for you to checkout my branch and test?

Best regards

**Comment by Youbi42** [comment]
It works!!!
I had used `en.ts` as base template for `fr.ts`, I was so wrong :D
I rewrote `fr.ts` from `nl.ts`, and voilà!
I’ll come back to you when my translation is complete.

Thanks for your help :smiley:

**Comment by blakevanlan** [comment]
Glad you got it working!

@gillesgros uploaded a zip of languages files that you might find useful: [messages-fr.zip](https://github.com/blakevanlan/KingdomCreator/files/4319039/messages-fr.zip)

**Comment by gillesgros** [comment]
@blake : I have all the images in french. How do you want them packaged ?

@Youbi42  : have a look at https://71yeti.fr

> @gillesgros uploaded a zip of languages files that you might find useful: messages-fr.zip
I have notices some typos. I will provide an update.

**Comment by blakevanlan** [comment]
@gillesgros Awesome! A zip is fine or you can open up a pull request. I'll probably name them all something along the lines of `{set}_{cardname}_{lang}.jpg` (ex: `adventures_caravanguard_fr.jpg`).

**Comment by gillesgros** [comment]
Hello here is the zip file

to avoid to have to duplicate image from baseset to baseset2  i use @error directive on img

I add my static-card.vue file as example


[static-card.zip](https://github.com/blakevanlan/KingdomCreator/files/4345379/static-card.zip)

image zip file : https://71yeti.fr/img/card.fr.zip

**Comment by Youbi42** [comment]
Nice card images @gillesgros :) That will be awesome to complete the translation ^^
@blakevanlan I’ve just opened pull request #42 which brings full french translation. A `npm run build` is necessary, I didn’t want to add changes on assets to the git history.

**Comment by gillesgros** [comment]
And a fix of typo in file cards.fr.json


[cards.fr.json.zip](https://github.com/blakevanlan/KingdomCreator/files/4346054/cards.fr.json.zip)

**Comment by blakevanlan** [comment]
Deployed in #43!

**Comment by blakevanlan** [comment]
@gillesgros where was the typo? Realized I deployed without merging in your changes.

**Comment by gillesgros** [comment]
silos, old witch and Piazza at least. were having typos.

**Comment by Youbi42** [comment]
I’m comparing and fixing my typos ^^
All french name were crawled from dominionstrategy, my quick check wasn’t enough for the translation to be perfect!

**Comment by Youbi42** [comment]
Thank you for your fixes, @gillesgros :) I checked your version against the « official » dominion.games cards, and fixed all the errors.
Let me know if I forgot something.

@blakevanlan fixes are ready to merge, see #44 :)

**Comment by blakevanlan** [comment]
Deployed French cards in PR #46!
